name: autoflake, isort, black

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Python Linter
      uses: jiwidi/python-lint-action@main
      with:
        autoflake-options: "--expand-star-imports --remove-all-unused-imports  --ignore-init-module-imports --remove-unused-variables --ignore-pass-after-docstring --in-place --verbose"
        black-options: "--verbose --line-length 120 -target-version py310"
        isort-options: "--profile black --line-length 120 --py 310 --remove-redundant-aliases --star-first"

    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
