name: pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up secrets file
        env:
          S3_SECRETS_FILE: ${{ secrets.S3_SECRETS_FILE }}
        run: |
          echo $S3_SECRETS_FILE > .env
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'
      - name: Poetry export requirements.txt file
        run: |
          python -m pip install poetry
          poetry export -f requirements.txt --output=requirements.txt --without-hashes --with=dev
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: platyrhynchos-action
          verbose: true
